name: Mocha Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        run: |
          yarn install --frozen-lockfile
          yarn test

      - name: Crypto experiment tests
        run: |
          cd programs/crypto-experiment
          cargo test
          cd ..
          cd ..

      - name: Eslint check
        run: yarn lint
