name: Mocha Tests

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn run test; yarn run testlib