name: Mocha Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Eslint check
        run: yarn lint

      - name: Run library test
        run: |
          yarn test

      - name: Crypto experiment tests
        run: |
          cd packages/crypto_experiment
          cargo test
          cd ..
          cd ..
